version: '3.8'

services:
  pg-master:
    image: postgres:17
    container_name: pg-master
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
    networks:
      - pg-net

  pg-replica:
    image: postgres:17
    container_name: pg-replica
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - replica_data:/var/lib/postgresql/data
    networks:
      - pg-net
    depends_on:
      - pg-master

volumes:
  master_data:
  replica_data:

networks:
  pg-net:
    driver: bridge